name: Notify Teams on PR

on:
  pull_request:
    types: [opened, edited]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Notify Teams based on selection
      id: notify_teams
      run: |
        set -e  # Stop execution if any command fails

        PR_BODY=$(jq -r '.pull_request.body' $GITHUB_EVENT_PATH)
        PR_URL=${{ github.event.pull_request.html_url }}

        echo "PR_BODY content:"
        echo "$PR_BODY"

        # Define a reusable function for sending notifications
        send_notification() {
          TEAM_NAME=$1
          SLACK_WEBHOOK=$2

          echo "Debugging: Notifying $TEAM_NAME."
          curl -X POST -H 'Content-type: application/json' --data "$(jq -n --arg url "$PR_URL" --arg team "$TEAM_NAME" '{"text": "A new PR has been created/updated that affects \($team): \($url)"}')" "$SLACK_WEBHOOK" || echo "Failed to notify $TEAM_NAME"

          # Send breaking changes to the team if present
          BREAKING_CHANGES=$(echo "$PR_BODY" | awk '/## Breaking Changes/{flag=1;next}/##/{flag=0}flag' | sed '/^\s*$/d')
          if [ ! -z "$BREAKING_CHANGES" ]; then
            echo "Sending breaking changes to $TEAM_NAME."
            curl -X POST -H 'Content-type: application/json' --data "$(jq -n --arg bc "$BREAKING_CHANGES" '{"text": "Breaking Changes: \($bc)"}')" "$SLACK_WEBHOOK" || echo "Failed to notify $TEAM_NAME about breaking changes"
          else
            echo "No breaking changes found for $TEAM_NAME."
          fi
        }

        # Check if Team A is selected and notify
        if [[ "$PR_BODY" == *"- [x] Team A"* ]]; then
          send_notification "Team A" "${{ secrets.NOTIFY_TEAM_A }}"
        else
          echo "Debugging: Team A is NOT selected."
        fi

        # Check if Team B is selected and notify
        if [[ "$PR_BODY" == *"- [x] Team B"* ]]; then
          send_notification "Team B" "${{ secrets.NOTIFY_TEAM_B }}"
        else
          echo "Debugging: Team B is NOT selected."
        fi

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
