name: Notify Teams on PR

on:
  pull_request:
    types: [opened, edited]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Read PR template
      id: read_pr_template
      run: |
        PR_BODY=$(jq -r '.pull_request.body' $GITHUB_EVENT_PATH)
        echo "::set-output name=pr_body::$PR_BODY"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Notify Teams based on selection
      id: notify_teams
      run: |
        PR_BODY="${{ steps.read_pr_template.outputs.pr_body }}"
        echo "$PR_BODY" | grep -q '\- \[x\] Team A';
        
        # Check if Team A is selected
        if echo "$PR_BODY" | grep -q '\- \[x\] Team A'; then
          echo "Sending notification to Team A"
          curl -X POST -H 'Content-type: application/json' --data '{"text":"A new PR has been created/updated that affects Team A: ${{ github.event.pull_request.html_url }}"}' ${{ secrets.NOTIFY_TEAM_A }}
        fi

        # Check if Team B is selected
        if echo "$PR_BODY" | grep -q '\- \[x\] Team B'; then
          echo "Sending notification to Team B"
          curl -X POST -H 'Content-type: application/json' --data '{"text":"A new PR has been created/updated that affects Team B: ${{ github.event.pull_request.html_url }}"}' ${{ secrets.NOTIFY_TEAM_B }}
        fi

        # Check if there are breaking changes
        BREAKING_CHANGES=$(echo "$PR_BODY" | awk '/## Breaking Changes/{flag=1;next}/##/{flag=0}flag' | sed '/^\s*$/d')

        if [ ! -z "$BREAKING_CHANGES" ]; then
          echo "Including breaking changes in the notification."
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Breaking Changes: '$BREAKING_CHANGES'"}' ${{ secrets.NOTIFY_TEAM_A }}
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Breaking Changes: '$BREAKING_CHANGES'"}' ${{ secrets.NOTIFY_TEAM_B }}
        fi
